name : Read Target file workflow
on: 
  push:
    branches:
      - main

jobs:
  read-file:
    runs-on: windows-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v2
        with:
          repository: owner/mounika-demo
          ref: main
          path: mounika-demo

      - name: Read Target file
        run: |
          cat mounika-demo/C:\Users\demounik\kpmg-1\mounika-demo/to/target-file.txt  
