name : Read Target file workflow
on: 
  push:
    branches:
      - main

jobs:
  read-file:
    runs-on: windows-latest
    steps:
      - name: checkout Repository
        uses: actions/checkout@v2
      - name: Read target file
        run: |
          curl -sSL
          https://github.com/Mounika-repo/Github-demo.git
          VALUE=$(grep "desired_pattern" ps1.txt)
          echo "$VALUE" >> captured_values.csv
